/* */
/* Created by joe on 6/23/25. */
/* */

#ifndef TEST_MUT_RLITT_RINGSHIFT_CONFIG_POSITIVE_TESTS_H
#define TEST_MUT_RLITT_RINGSHIFT_CONFIG_POSITIVE_TESTS_H
void test_config_positive(void);

#endif /* TEST_MUT_RLITT_RINGSHIFT_CONFIG_POSITIVE_TESTS_H */
