repos:
    - repo: local
      hooks:
          - id: docs
            name: docs
            language: system
            entry: rumdl check
            exclude:
                glob:
                    - ".github/**/*.*"
            files:
                glob:
                    - "**/*.md"
          - id: doxygen
            name: doxygen
            language: system
            entry: just check-doxygen
            pass_filenames: false
            exclude:
                glob:
                    - "libraries/**/*.*"
            files:
                glob:
                    - "**/*.c"
                    - "**/*.h"
                    - "**/*.cpp"
                    - "**/*.hpp"
          - id: uncrustify
            name: uncrustify
            language: system
            entry: uncrustify -c .uncrustify.cfg --check -q
            exclude:
                glob:
                    - "libraries/**/*.*"
            files:
                glob:
                    - "**/*.c"
                    - "**/*.h"
                    - "**/*.hpp"
                    - "**/*.cpp"
          - id: cmake-format
            name: cmake-format
            language: system
            entry: cmake-format --check
            exclude:
                glob:
                    - "libraries/**/*.*"
            files:
                glob:
                    - "**/CMakeLists.txt"
                    - "libraries/CMakeLists.txt"
          - id: check-cppcheck
            name: cppcheck
            language: system
            entry: just check-cppcheck
            pass_filenames: false
            exclude:
                glob:
                    - "libraries/**/*.*"
            files:
                glob:
                    - "**/*.c"
                    - "**/*.h"
                    - "**/*.cpp"
                    - "**/*.hpp"
