site_name: "The Tanglenomicon: Core Libraries"
site_description: A toolchain for generating RLITT
site_url: https://joe-starr.com/
theme:
    name: material
    palette:
        # Dark Mode
        - scheme: slate
          toggle:
              icon: material/weather-sunny
              name: Dark mode
          primary: purple
          accent: deep purple

        # Light Mode
        - scheme: default
          toggle:
              icon: material/weather-night
              name: Light mode
          primary: purple
          accent: deep purple
    features:
        - navigation.indexes
repo_name: Uiowa-Applied-Topology/tanglenomicon_rlitt_runner
repo_url: https://github.com/Uiowa-Applied-Topology/tanglenomicon_rlitt_runner
extra_css:
    - https://unpkg.com/katex@0/dist/katex.min.css
    - "admonitions.css"

extra_javascript:
    - https://unpkg.com/katex@0/dist/katex.min.js
    - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
    - "extra.js"

watch:
    - docs
    - source

plugins:
    - gh-admonitions:
    - search:
    - include-files:
          temp_location: Libraries
          search_syntax:
              - "**/*.md"
              - "**/media/*.*"
          search_paths:
              - source
    # - mkdoxy:
    #       projects:
    #           core_lib: # name of project must be alphanumeric + numbers (without spaces)
    #               src-dirs: ./source/ # path to source code (support multiple paths separated by space) => INPUT
    #               full-doc: True # if you want to generate full documentation
    #               doxy-cfg: # standard doxygen configuration (key: value)
    #                   FILE_PATTERNS: "*.c *.h" # specify file patterns to filter out
    #                   RECURSIVE: True # recursive search in source directories

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true
    - toc:
          permalink: 
          separator: "_"
    - admonition
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
          options:
              custom_icons:
                  - overrides/.icons
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/Uiowa-Applied-Topology/tanglenomicon_rlitt_runner
