site_name: "The Tanglenomicon: Core Libraries"
site_description: A toolchain for generating RLITT
site_url: https://joe-starr.com/
theme:
    name: material
    features:
        - navigation.indexes
repo_name: Uiowa-Applied-Topology/tanglenomicon_rlitt_runner
repo_url: https://github.com/Uiowa-Applied-Topology/tanglenomicon_rlitt_runner
extra_css:
    - https://unpkg.com/katex@0/dist/katex.min.css
    - "admonitions.css"

extra_javascript:
    - https://unpkg.com/katex@0/dist/katex.min.js
    - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
    - "extra.js"

watch:
    - docs
    - source

plugins:
    - gh-admonitions:
    - search:
    - autorefs:
    - awesome-nav:
          resolve_closest: true
    - include-files:
          temp_location: Libraries
          search_syntax:
              - "**/*.md"
              - "**/media/*.*"
              - "**/.nav.yml"
          search_paths:
              - source
    - bibtex:
          bib_file: "docs/ref.bib"
    - mkdocstrings:
          handlers:
              c:
                  options:
                      dosomething: yes
markdown_extensions:
    - attr_list
    - footnotes
    - pymdownx.arithmatex:
          generic: true
    - toc:
          permalink: 
          separator: "_"
    - admonition
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
          options:
              custom_icons:
                  - overrides/.icons
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/Uiowa-Applied-Topology/tanglenomicon_rlitt_runner
