//
// Created by joe on 4/25/25.
//

#ifndef TEST_NOTATION_AWPTT_DECODE_NEGATIVE_TESTS_H
#define TEST_NOTATION_AWPTT_DECODE_NEGATIVE_TESTS_H
void test_decode_negative(void);

#endif // TEST_NOTATION_AWPTT_DECODE_NEGATIVE_TESTS_H
