//
// Created by joe on 4/25/25.
//

#ifndef TEST_NOTATION_AWPTT_ENCODE_POSITIVE_TEST_H
#define TEST_NOTATION_AWPTT_ENCODE_POSITIVE_TEST_H

void test_encode_positive(void);

#endif // TEST_NOTATION_AWPTT_ENCODE_POSITIVE_TEST_H
