name: QA Pipeline

on:
    pull_request:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  fetch-depth: 0

            - name: Check Nixpkgs inputs
              uses: DeterminateSystems/flake-checker-action@main
              with:
                  fail-mode: true

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - name: Build
              run: |
                  nix develop --command \
                      just build_all

            - name: Check
              run: |
                  nix develop --command \
                      just check

            - name: Test
              run: |
                  nix develop --command \
                    just test_all

            - name: Build html
              run: |
                  nix develop --command \
                    just html

    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  fetch-depth: 0 # GitHub Actions example:

            - uses: MinoruSekine/setup-scoop@v4.0.2
              name: Install scoop with uutils-coreutils
              with:
                  buckets: extras
                  apps: uutils-coreutils

            - name: Install python requirements
              run: pip install -r requirements.txt

            - name: Install lizard
              run: pip install lizard

            - name: Build cmake
              shell: cmd
              run: cmake -B.\.build\Release -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_COLOR_DIAGNOSTICS=TRUE -G Ninja

            - name: Build source
              shell: cmd
              run: cmake --build .\.build\Release -j

            - name: run tests
              shell: cmd
              run: |
                  python .\misc\test_scripts\win_runner.py
