/* */
/* Created by joe on 6/23/25. */
/* */

#ifndef TEST_COMP_RLITT_POSITIVITY_CONFIG_POSITIVE_TESTS_H
#define TEST_COMP_RLITT_POSITIVITY_CONFIG_POSITIVE_TESTS_H
void test_config_positive(void);

#endif /* TEST_COMP_RLITT_POSITIVITY_CONFIG_POSITIVE_TESTS_H */
